spring.application.name=acmemoda

# PostgreSQL properties
# spring.datasource.url=jdbc:mysql://localhost:3306/acmemoda
# spring.datasource.username=root
# spring.datasource.password=
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# # Hibernate properties
# logging.level.org.hibernatee.sql=debug
# spring.jpa.show-sql=true
# spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/moda
spring.datasource.username=root
spring.datasource.password=qwerty12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true 